### PR TITLE
[CHANGE] Basic TYPO3 12.4 compatibility

### PR DESCRIPTION
**Pull request by marcelmarty**

### CODE REVIEW

**Comment by h3nn3s** [comment]
Hi @marcelmarty 
thanks for your PR - after a quick jump over the changes I have two things to mention:
Currently I am lacking time to really test it.

- Using "TYPO3" Constant would cause TYPO3 v10 to fail - so the version constraints in ext_emconf.php and composer.json should be set to be compatible with v11 and v12
- page_language_overlay table is obsolete, nowadays. Do we really need this anymore?

**Comment by marcelmarty** [comment]
Let me check if page_language_overlay is still needed. I don't think so.

**Comment by marcelmarty** [comment]
@h3nn3s I updated the two things you mentioned.

**Comment by marcelmarty** [comment]
Unfortunately.. There is another issue in the frontend:
image

I'm working on this.

**Comment by marcelmarty** [comment]
@h3nn3s Now it is working with TYPO3 v12.4. Let me final double check tomorrow with TYPO3 11.5.

**Comment by h3nn3s** [comment]
better late than never... Thanks for your contribution.

**Pull request merged**
